[package]
name = "z-new"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
dotenv = "0.15.0"
hyper = "1.8.1"
reqwest = "0.13.1"
serde = "1.0.228"
serde_json = "1.0.148"
tokio = { version = "1.48.0", features = ["full"] }
